# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file into the container at /usr/src/app
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's source code into the container at /usr/src/app
COPY . .

# Expose the port that the application will run on
EXPOSE 8000

# Define the command to run your application
CMD ["gunicorn", "-b", "0.0.0.0:8000", "myapp.wsgi:application"]
# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file into the container at /usr/src/app
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's source code into the container at /usr/src/app
COPY . .

# Expose the port that the application will run on
EXPOSE 8000

# Define the command to run your application
CMD ["gunicorn", "-b", "0.0.0.0:8000", "myapp.wsgi:application"]
